import "./globals.css";
import type { Metadata } from "next";
import HeroUIWrapper from "@/providers/HeroUIWrapper";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <HeroUIWrapper>
        {children}
        </HeroUIWrapper>
      </body>
    </html>
  );
}
